Dev
stepancar-web-programming/2023-fall-lab-portfolio-miroyan-e.-a. pull request #3
Opened 2024-01-04 16:17 UTC by mir0yan

2024-01-07 06:08 UTC, stepancar commented on .vscode/settings.json
> +    "liveServer.settings.port": 5501
Кажется имеет отношение к вашему локальному конфигу, не имеет смысла для других разработчиков

2024-01-07 06:11 UTC, stepancar commented on assets/js/script.js
> +  let currentSlidePos = 0;
обратите внимание на то, что ваши идентификаторы доступны извне. 
Давайте изолируем вашу программу, помните, у нас в рубежной работе есть отдельный вопрос посвященный этому. Попробуйте подумать к чему может привести если этого не сделать

2024-01-07 06:25 UTC, stepancar commented on index.html
> +            <a  class="navbar-link" id="home-button">Home</a>
обратите внимание как ведет себя клавиатурная навигация в этом элементе. Если вы нажмете на таб - вы заметите что только последний пункт меню доступен для навигации с клавиатуры.
Так же заметьте, что только при наведении на него, курсор выглядит как указатель.
Давайте сделаем навигацию доступной.
Так же заметить еще один момент. при нажатии на ссылку страницу скроллит в правильное место, однако урл не меняется, хотя по факту, вы совершили навигацию. В стандартной бразерной навигации предполагается что вы можете кнопками вперед назад ходить по вашим навигациям. Так же было бы здорово если можно будет скопировать ссылку на конкретный раздел.

2024-01-07 06:26 UTC, stepancar commented on assets/js/script.js
> +  HomeSection.scrollIntoView(true)
Обратите внимание на то как работают hash ссылки

2024-01-07 06:27 UTC, stepancar requested changes
Оставил комментарии

2024-01-14 21:18 UTC, mir0yan commented on .vscode/settings.json
> +    "liveServer.settings.port": 5501
6c7ebf5d2899ff3ed0b09ba40f49d3347af5e0e0

2024-01-14 22:00 UTC, mir0yan commented on assets/js/script.js
> +  let currentSlidePos = 0;
aa31550c61d29910e97e5c42eee82dcb6b6c810f

2024-01-15 00:04 UTC, mir0yan commented on index.html
> +            <a  class="navbar-link" id="home-button">Home</a>
c0f3acd0f13d4b2224f21bc088d032d94a1c5bf6

2024-01-15 00:08 UTC, mir0yan commented on index.html
> +            <a  class="navbar-link" id="home-button">Home</a>
в safari локально работает, а в pages - нет, хотя в chrome  все норм

2024-01-16 07:13 UTC, stepancar commented on index.html
> +            <a  class="navbar-link" id="home-button">Home</a>
@mir0yan , обратите внимание на то, что вам пришлось реализовать обработчики руками.
В изначальной имплментации, которую я комментировал, элементы были не навигируемыми, потому что у ссылок не было аатрибута href. Если его установить в #id элемента для скролла - у вас было бы довольно акцессабильное решение, не требующее js кода

2024-01-16 08:24 UTC, stepancar approved these changes

2024-01-18 08:11 UTC, merged